;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	copy-from-above-command
	counsel-M-x
	counsel-yank-pop
	org-kill-line
	org-self-insert-command
	org-shiftdown
	org-shiftup
	wdired--self-insert
	wdired-finish-edit
	))

(setq mc/cmds-to-run-once
      '(
	org-end-of-line
	))
